python train_cosAnn.py --max_epoch=30 --save_interval=30
python inference.py --pretrain='30Epoch.pth' --output_name='30Epoch_cosAnn.csv'
python train_cosAnn.py --max_epoch=40 --save_interval=40
python inference.py --pretrain='40Epoch.pth' --output_name='40Epoch_cosAnn.csv'
python train_cosAnn.py --max_epoch=50 --save_interval=50
python inference.py --pretrain='50Epoch.pth' --output_name='50Epoch_cosAnn.csv'
python train_cosAnn.py --max_epoch=60 --save_interval=60
python inference.py --pretrain='60Epoch.pth' --output_name='60Epoch_cosAnn.csv'
python train_cosAnn.py --max_epoch=70 --save_interval=70
python inference.py --pretrain='70Epoch.pth' --output_name='70Epoch_cosAnn.csv'